name: Generate 30 Days of Mapping challenges

on:
  workflow_dispatch:
  push:
    paths:
      - 'signup/30 Days of Mapping Sign-up.xlsx'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate challenges from signup sheet
        run: |
          python scripts/generate_challenges.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: generate challenge folders & READMEs from signup sheet'
          branch: chore/generate-challenges
          title: 'Generate challenge folders & READMEs from signup sheet'
          body: |
            This PR was created automatically by the workflow to generate one folder per challenge under `challenges/` and a README.md in each folder with date, title, description, and members.
          add-paths: |
            challenges/**
          labels: |
            automation
            data-sync

